name: thomasstrub
favicon: null
layout_spectrum: 0.7265176
typography_spectrum: 0.1803224
title: Thomas Strub Fotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07289314
  lightness: 0.7730673
  saturation: 0.2536183
  rhythmicContrast: 0.1964205
purpose: []
